# Copyright 2015-2019 Rene Rivera.
# Copyright 2019 Mateusz Loskot <mateusz at loskot dot net>
# Copyright 2020 Alexander Grund
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

#
# Generic Azure Pipelines build script for boostorg repositories
# See: https://github.com/boostorg/boost-ci/
#
# Instructions for customizing this script for your library:
#
# 1. Customize the compilers and language levels you want.
# 2. If you have more than include/, src/, test/, example/, examples/,
#    benchmark/ or tools/ directories, set the environment variable DEPINST.
#    For example if your build uses code in "bench/" and "fog/" directories:
#      - DEPINST: --include bench --include fog
# 3. Enable pull request builds in your boostorg/<library> account.
#
# That's it - the script will do everything else for you.

trigger:
  branches:
    include:
    - develop
    - master
    - bugfix/*
    - feature/*
    - fix/*
    - pr/*

pr:
  branches:
    include:
    - develop

variables:
  B2_CI_VERSION: 1
  B2_VARIANT: release,debug
  B2_LINK: shared,static
  B2_FLAGS: "warnings=extra warnings-as-errors=on"

stages:

- stage: Test
  jobs:
  
  - job: 'macOS'
    pool:
      vmImage: 'macOS-10.14'
    strategy:
      matrix:
        Xcode_11_3_1:
          B2_TOOLSET: clang
          B2_CXXSTD: 14,17,2a
          XCODE_APP: /Applications/Xcode_11.3.1.app
        Xcode_11_2_1:
          B2_TOOLSET: clang
          B2_CXXSTD: 14,17,2a
          XCODE_APP: /Applications/Xcode_11.2.1.app
        Xcode_11_2:
          B2_TOOLSET: clang
          B2_CXXSTD: 14,17,2a
          XCODE_APP: /Applications/Xcode_11.2.app
        Xcode_11_1:
          B2_TOOLSET: clang
          B2_CXXSTD: 14,17,2a
          XCODE_APP: /Applications/Xcode_11.1.app
        Xcode_10_3:
          B2_TOOLSET: clang
          B2_CXXSTD: 11,14,17,2a
          XCODE_APP: /Applications/Xcode_10.3.app
        Xcode_10_2_1:
          B2_TOOLSET: clang
          B2_CXXSTD: 11,14,17,2a
          XCODE_APP: /Applications/Xcode_10.2.1.app
        Xcode_10_2:
          B2_TOOLSET: clang
          B2_CXXSTD: 11,14,17,2a
          XCODE_APP: /Applications/Xcode_10.2.app

        # These get mysterious link errors for std::basic_string members
        #Xcode_10_1:
        #  B2_TOOLSET: clang
        #  B2_CXXSTD: 11,14,17,2a
        #  XCODE_APP: /Applications/Xcode_10.1.app
        #Xcode_10_0:
        #  B2_TOOLSET: clang
        #  B2_CXXSTD: 11,14,17,2a
        #  XCODE_APP: /Applications/Xcode_10.app

    steps:
    - bash: |
        set -e

        git clone --branch master https://github.com/boostorg/boost-ci.git boost-ci-cloned
        cp -prf boost-ci-cloned/ci .
        rm -rf boost-ci-cloned
        source ci/azure-pipelines/install.sh
      displayName: Install
    - bash: |
        set -e
        echo "SELF=$SELF"
        echo "BOOST_ROOT=$BOOST_ROOT"

        cd $BOOST_ROOT/libs/$SELF
        ci/azure-pipelines/build.sh
      displayName: 'Build'
